bl31: set LIBBASE flag
ATF default branch is now on aiot-v2.6, we need to set LIBBASE flag.

Otherwise we have compilation errors, for example on i350 we have
multiple definitions error:
/home/julien/Documents/Baylibre/mediatek/bootloaders/toolchains/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf/bin/../lib/gcc/aarch64-none-elf/10.3.1/../../../../aarch64-none-elf/bin/ld: /home/julien/Documents/Baylibre/mediatek/bootloaders/libbase-prebuilts/mt8365/libbase.a(mt_base.c.o): in function `mtk_get_hwid':
/usr/src/debug/libbase/1.0-r0/libbase-1.0/../../../../../../workspace/sources/libbase/mt_base.c:20: multiple definition of `mtk_get_hwid'; /home/julien/Documents/Baylibre/mediatek/bootloaders/arm-trusted-firmware/build/mt8365/debug/bl31/mtk_hwid.o (symbol from plugin):(.text+0x0): first defined here

Signed-off-by: Julien Masson <jmasson@baylibre.com>